INSERT INTO users (name, email, password) VALUES ('Jackson Poluck', 'magic@gathering.org', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');
INSERT INTO users (name, email, password) VALUES ('John Oman', 'good_mythical@morning.org', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');
INSERT INTO users (name, email, password) VALUES ('Percy Jackson', 'carolina@mreaper.org', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, street, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, city, province, post_code) VALUES (1, 'Bellview Hospital','description', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Tardis_BBC_Television_Center.jpg/1280px-Tardis_BBC_Television_Center.jpg','https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Tardis_BBC_Television_Center.jpg/1280px-Tardis_BBC_Television_Center.jpg', 20, '13 REAL St', 12, 4, 5, 'Canada', 'Vancouver', 'BC', 'V8F4R5');
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, street, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, city, province, post_code) VALUES (2, 'Cozy Mansion','description', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Tardis_BBC_Television_Center.jpg/1280px-Tardis_BBC_Television_Center.jpg','https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Tardis_BBC_Television_Center.jpg/1280px-Tardis_BBC_Television_Center.jpg', 50, '23 Tadanac Rd', 6, 3, 8, 'Canada', 'Vancouver', 'BC', 'C6H56Z')
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, street, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, city, province, post_code) VALUES (3, 'Huge Cottage','description', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Tardis_BBC_Television_Center.jpg/1280px-Tardis_BBC_Television_Center.jpg','https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Tardis_BBC_Television_Center.jpg/1280px-Tardis_BBC_Television_Center.jpg', 100, '67 Power St', 3, 1, 1, 'Canada', 'Vancouver', 'BC', 'D8JF6Z');
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2018-02-12T08:00:00.000Z', '2018-04-20T07:00:00.000Z', 1, 1);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2018-04-12T09:00:00.000Z', '2018-05-20T011:00:00.000Z', 2, 2);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2018-03-12T11:00:00.000Z', '2018-07-20T08:00:00.000Z', 3, 3);
INSERT INTO property_reviews (rating, message) VALUES (5, 'Surprisingly bigger on the inside');
INSERT INTO property_reviews (rating, message) VALUES (5, 'Surprisingly bigger on the inside');
INSERT INTO property_reviews (rating, message) VALUES (5, 'Surprisingly bigger on the inside');